#!/usr/bin/expect

set timeout -1

spawn -noecho ./bin/winaxshell ;

proc type_command {text} {
    expect -re ".*\\$ "

    set send_human {.1 .3 .1 .1 .1}
    send_user -h "$text\n"
    
    send -- "$text\r"
    sleep 1.5
}

type_command "echo 'Welcome to the WinAxShell!'"
type_command "ls -l"
type_command "ps f | nl | nl | nl | nl"
type_command "ls -l | head -n 5 | tail -n 3 | wc -l && echo 'Test chained pipes OK'"
type_command "exit"
expect -re "Bye! Thanks for using WinAxShell!"
