#!/usr/bin/expect

set timeout -1

spawn -noecho ./bin/winaxshell

proc type_command {text} {
    # Wait for winaxshell prompt
    expect -re ".*\\$ "

    set send_human {.05 .1 .05 .05 .05}
    send_user -h "$text\n"

    send_user -- "Command : "
    send -- "$text\r"
    sleep 1
}

set cmdfile "./hack/list_commands.txt"
set fd [open $cmdfile r]

while {[gets $fd line] >= 0} {
    set line [string trim $line]
    if {$line eq "" || [regexp {^#} $line]} {
        continue
    }
    type_command $line
}
close $fd

type_command "exit"
expect -re "Bye! Thanks for using WinAxShell!"
