name: CI WinAxShell

on:
  push:
    paths:
      - 'winaxshell/**'
  pull_request:
    paths:
      - 'winaxshell/**'

defaults:
  run:
    working-directory: winaxshell
    shell: bash

jobs:
  prepare:
    runs-on: ubuntu-22.04
    container:
      image: gcc:14.2.0
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          apt-get update && apt install -y libcriterion-dev

  build:
    runs-on: ubuntu-22.04
    container:
      image: gcc:14.2.0
    needs: prepare
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: make

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: winaxshell/bin/

  test:
    runs-on: ubuntu-22.04
    container:
      image: gcc:14.2.0
    needs: [prepare, build]
    steps:
      - uses: actions/checkout@v3

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: winaxshell/bin/

      - name: Set execute permissions for test executable
        run: chmod +x winaxshell/bin/winaxshell_tests

      - name: Run unit & integration tests
        run: make tests